<a href="https://colab.research.google.com/github/sheikh-asiful-islam/Pandas_Playground/blob/main/Pandas_Playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# rename pandas as pd
import pandas as pd

In [ ]:
# 2 main data types (1.Series and 2.DataFrame)
series = pd.Series(["BMW", "Toyota", "Honda"])

In [ ]:
series

0       BMW
1    Toyota
2     Honda
dtype: object

In [ ]:
# series = 1 -dimentional

In [ ]:
colours = pd.Series(["red", "Blue", "White"])
colours

0      red
1     Blue
2    White
dtype: object